# @package _global_

defaults:
  - paths: default
  - hydra: default
  - model: default
  - data: default
  - trainer: default
  - callbacks: default
  - logger: wandb
  - _self_

  - experiment: null

pipeline: train  # [train, val, cv]
seed: 42
