# @package _global_

defaults:
  - paths: default
  - hydra: default
  - model: default
  - data: default
  - trainer: default
  - callbacks: default
  - logger: wandb
  - _self_

  - experiment: null

tags: ["train"]

pipeline: train
seed: 42
