_target_: icecube.model.lstm.LSTM

defaults:
  - optimizer: adam
  - scheduler: plateau
  - criterion: crossentropy

input_size: 6
hidden_size: 192
num_bins: ${data.num_bins}
num_layers: 1
bias: false
batch_first: true
dropout: 0
bidirectional: false
task: clf
net_name: lstm

scheduler_conf:
  monitor: val/loss
  interval: epoch
  frequency: 1