_target_: icecube.model.transformer.TransformerClassifier


defaults:
  - optimizer: adam
  - scheduler: plateau
  - criterion: crossentropy

input_size: 9
embed_dim: 64
nhead: 4
feedforward_dim: 256
output_size: 256
batch_first: true
dropout: 0.1
task: clf