defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progressbar.yaml
  - lr_monitor.yaml
  - _self_

model_checkpoint:
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/mae"
  mode: min
  save_last: True
  save_top_k: 5
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/mae"
  patience: 50
  mode: min

model_summary:
  max_depth: -1